name: NYC 14-Day ( Hourly )

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install pytz
        run: |
          pip install pytz

      - name: Generate Metadata
        id: metagen
        run: |
          python -c "from datetime import datetime, timedelta
          from pytz import timezone
          zone = timezone('US/Eastern')
          now = datetime.now(tz=zone).replace(minute=0, second=0, microsecond=0)
          target = now - timedelta(days=1)
          
          fname = target.strftime('NYC_%Y-%m-%d')
          timestr = 'Forecast for ' + target.strftime('%Y-%m-%d')
          month = str(now.strftime('%m'))
          day = str(now.strftime('%d'))
          year = str(now.strftime('%Y'))
          
          print(f'::set-output name=fname::{fname}')
          print(f'::set-output name=timestr::{timestr}')
          print(f'::set-output name=month::{month}')
          print(f'::set-output name=year::{year}')"

      - name: Check Directory
        run: |
          mkdir -p $YEAR/$MONTH
        env:
          YEAR: ${{ steps.metagen.outputs.year }}
          MONTH: ${{ steps.metagen.outputs.month }}

      - name: Download JSON
        run: |
          curl -o $YEAR/$MONTH/$FILENAME.json "https://api.open-meteo.com/v1/forecast?latitude=$LAT&longitude=$LON&hourly=temperature_2m,relativehumidity_2m,dewpoint_2m,apparent_temperature,precipitation_probability,rain,showers,snowfall,surface_pressure,cloudcover,windspeed_10m,winddirection_10m,windgusts_10m&temperature_unit=fahrenheit&windspeed_unit=mph&precipitation_unit=inch&timezone=auto&past_days=1&forecast_days=1"
        env:
          LAT: 40.71033
          LON: -73.99307
          YEAR: ${{ steps.metagen.outputs.year }}
          MONTH: ${{ steps.metagen.outputs.month }}
          FILENAME: ${{ steps.metagen.outputs.fname }}

      - name: Split JSON
        run: |
          python -c "import os
          import json
      
          repo_directory = os.environ['GITHUB_WORKSPACE']
          with open(repo_directory + '/$YEAR/$MONTH/' + '$FILENAME.json') as f:
              data = json.load(f)
              for key in list(data['hourly'].keys()):
                  data['hourly'][key] = data['hourly'][key][:24]
          with open(repo_directory + '/$YEAR/$MONTH/' + '$FILENAME.json', 'w') as f:
              json.dump(data, f, indent=4, ensure_ascii=False)
          "
        env:
          YEAR: ${{ steps.metagen.outputs.year }}
          MONTH: ${{ steps.metagen.outputs.month }}
          FILENAME: ${{ steps.metagen.outputs.fname }}
        
      - name: Commit Changes
        run: |
          git config user.name 'Climate-Cache'
          git config user.email 'theclimatecache@gmail.com'
          git add .
          git commit -m "${{ steps.metagen.outputs.timestr }}"
          git push origin HEAD:main
        env:
          GIT_SSH_KEY: ${{ secrets.PAT_TOKEN }}
